### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by levidurfee** [bulldogcreative/strype#36]
- [ ] #1 - Optional ID Param
- [ ] #7 - Orders
- [ ] #20 - Switch to Stripe::update()
- [ ] #33 - Use Factory Pattern for Models
